#!/bin/sh

lein run -m gen

rm -rf /tmp/html
cp -r ./html /tmp/
git clean -dfx
git checkout gh-pages
rm -rf ./css
mv /tmp/html/* ./
git add .
git commit -am 'Updated gh-pages'
git push origin

git checkout master
